ALTER TABLE vendas ADD COLUMN IF NOT EXISTS versao BIGINT;

UPDATE vendas SET versao = 0 WHERE versao IS NULL;

ALTER TABLE vendas ALTER COLUMN versao SET NOT NULL;
ALTER TABLE vendas ALTER COLUMN versao SET DEFAULT 0;
